# fly.toml file generated for chronibot-v2 on 2023-03-28T02:03:12+02:00

app = "chronibot-v2"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "arn"
processes = []

[env]
  BOT_PREFIX = "rubi"
  RANDOM_CHAT_CHANCE = "0.01"

[experimental]
  auto_rollback = false
